# WEEK1 - Python for Data Science 
# Day1 - Numpy Array/n-d array

## What is NumPy?
NumPy(NUmerical Python) is a python library used for numerical computing.It provides a powerful multidimensional array(ndarray) and many mathematical functions.
## Why NumPy?
- Faster than Python lists
- Less memory usage
- Supports vectorized operations
- Used in Data Science and Machine Learning

In [7]:
import numpy as np

In [24]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.zeros((2,2))
arr3

array([[0., 0.],
       [0., 0.]])

In [11]:
arr4 = np.ones((3,4))
arr4               

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#np.arange(start, end, step)--> include the frist by default
arr6 = np.arange(5,10,2)
arr6

array([5, 7, 9])

In [19]:
#np.linspace(lower range, upper range, jump)
arr7 = np.linspace(2,3,10)
arr7

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [21]:
arr8 = arr6.copy()
arr8

array([5, 7, 9])

# Numpy Arrays Properties and Attributes 
* shape
* nDim
* size
* Itemsize
* Dtype
* astype()

In [24]:
arr1.shape

(5,)

In [25]:
arr2.shape


(2, 3)

In [27]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
arr9.shape    # its a 3d matrix

(2, 2, 2)

In [31]:
arr9.ndim

3

In [34]:
arr9.size

8

In [43]:
arr9.itemsize  # this should give ans 4

8

In [45]:
arr7.dtype

dtype('float64')

In [46]:
arr9.dtype

dtype('int64')

In [47]:
arr9.astype('float')  #explicitly change data type

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# PYTHON LIST VS NUMPY ARRAYS 
* NA are Faster
* NA are COnvenient
* NA has Less Memory

In [8]:
lista = range(100)
arr11 = np.arange(100)

In [9]:
import sys

In [10]:
print(sys.getsizeof(87)*len(lista))

2800


In [11]:
print(arr11.itemsize*arr11.size)

800


In [12]:
import time

In [15]:
x= range(100000000)
y=range(100000000, 200000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

2.240435838699341


In [16]:
a = np.arange(100000000)
b = np.arange(100000000, 200000000)

start_time = time.time()
c = a + b

print(time.time()-start_time)

1.0889201164245605


# Indexing, SLicing and Iteration

In [31]:
arr12 = np.arange(24).reshape(6,4) #(rows,col)--factors of 24 in matrix
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr12[2] # this will give a row

array([ 8,  9, 10, 11])

In [44]:
arr12[:,1:4] # thi will give coloumn  

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [45]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [47]:
 for i in arr12: # this will print whole item in rows
     print(i) 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [52]:
# iteration
for i in np.nditer(arr12):     # this will print whole item in columns
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Advantages of NumPy
vshsbvhsbvik
vbshvbsjhvbfsjhvbfdjhvbdvjbdskv

# MINI PROJECT 
## (Student Mark Analysis)

In [54]:
import numpy as np

In [61]:
marks = np.array([48, 37, 95, 89, 67, 98])
print("Original marks = ", marks)

Original marks =  [48 37 95 89 67 98]


In [62]:
print("Total number of students = ", marks.size)

Total number of students =  6


In [68]:
marks[0] # marks of first student

np.int64(48)

In [65]:
print("MArks of last student = ", marks[5]) #marks of last one

MArks of last student =  98


In [67]:
marks[:4] # marks of first four students 

array([48, 37, 95, 89])

In [70]:
marks[-3:] # last three students

array([89, 67, 98])

In [78]:
marks + 5 # Increase every students marks by 5

array([ 53,  42, 100,  94,  72, 103])

In [79]:
marks * 2  #multiply by 2 to evry marks

array([ 96,  74, 190, 178, 134, 196])

## Observation

NumPy performs mathematical operations on the entire array at once without using loops, making the code simpler and faster.
